# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Only create Brand table - other tables already exist
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marka Adı')),
                ('category', models.CharField(choices=[('DERMO', 'Dermo-Kozmetik'), ('ILAC', 'İlaç'), ('VITAMIN', 'Vitamin/Takviye'), ('MAMA', 'Mama'), ('OTHER', 'Diğer')], default='OTHER', max_length=20, verbose_name='Kategori')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Marka')),
                ('product_count', models.IntegerField(default=0, verbose_name='Ürün Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
    ]
